第3章の章末演習問題

### [1] list(range(9))からテンソルaを作成して、サイズ、オフセット、ストライドを確認してください。
※ ここではGoogle Colaraboratoryでの実行を想定しています。


#### （a） b = a.view(3, 3)を使って新しいテンソルを作成します。viewはどんな動作をするのか？またaとbが同じストレージを共有していることを確認してください。

In [ ]:
# 回答

In [1]:
import numpy as np
import torch 

a = torch.arange(0,9)
b = a.view(3,3)

id(a.storage()) == id(b.storage())

True

In [9]:
print(a)
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
# このように、変数aとbは同じストレージの値を参照していますが、テンソルの形が異なっており、この形の変形はa.view(3.3)で実行されています

    #### （b） テンソル c = b[1:,1:]を作成し、サイズ、オフセット、ストライドを確認してください

In [ ]:
# 回答

In [2]:
c = b[1:,1:]
print(f"size: {c.size()}\n", f"offset: {c.storage_offset()}\n", f"stride: {c.stride()}\n")

size: torch.Size([2, 2])
 offset: 4
 stride: (3, 1)



### [2] torch ライブラリからcosineやsquare rootのような数学の演算に対応する関数を見つけてください。

#### （a） 関数を要素ごとに変数aに適用してください。なぜエラーが発生するのでしょう？

In [ ]:
# 回答


In [7]:
# これはエラー：float型にする
print(torch.cos(a))


RuntimeError: cos_vml_cpu not implemented for 'Long'

In [ ]:
# aがLong型である点が問題です

#### （b） 関数を実行可能にするために、どのような操作が必要なのでしょうか？

In [6]:
# 回答

In [5]:
# float型にする
print(torch.cos(a.float()))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])


#### （c） 何か自作の関数があれば、動かしてみましょう。

In [ ]:
# 省略

以上。
